DROP TABLE  TB_CSTM;

CREATE TABLE TB_CSTM
(
   CSTM_ID      VARCHAR(20) PRIMARY KEY,
   CSTM_NM    VARCHAR(100),
   CSTM_AGE    VARCHAR(3),
   CSTM_GND   VARCHAR(1),
   CSTM_PN     VARCHAR(20),
   CSTM_ADR   VARCHAR(1000) );